/* contentsWidget_data.js */

var structure = {
	"section" : [
		{"title" : "The Beginning", "chapter" : [
			{"title" : "Monday"},
			{"title" : "Tuesday"}
		]},
		{"title" : "The Middle", "chapter" : [
			{"title" : "Wednesday"},
			{"title" : "Thursday"},
			{"title" : "Friday"}
		]},
		{"title" : "The End", "chapter" : [
			{"title" : "Saturday"},
			{"title" : "Sunday"}
		]}
	]
}

var summary = {
    "summary" : [
		{"title": "The Beginning", "descrip": "<p><b>The year: </b>2050</p><p><b>The place: </b>A high-tech office in Vancouver, British Columbia, Canada</p><p><b>The characters: </b>Office mates and their robotic stand-ins. (See the Characters page)</p><p><b>The plot: </b>Two colleagues try to keep their illegal romance under the radar. Communications are mediated by artificially intelligent avatars, which accelerates the pace of events but also introduces some weird misunderstandings as well. The emotional storm blows over in a week, with some regrets but also affirmation for all parties involved.</p><p><b>The theme: </b>This is about the persistence of desire, power, ambition and love, even as people turn over more of the practicalities of daily life to their machines. This is not a dystopian story, but neither does it have a happy ending.</p><p><b>The method: </b>Groups of characters are introduced and daily life in 2050 is illustrated by example. People and situations are recognizable (some things never change), even amongst the amazing new gadgetry and unfamiliar social organization. Each group constitutes a subplot. We expect that things will get more complicated as the subplots converge and affect each other.</p>"},	    	
		{"title": "The Middle", "descrip": "<p><b>The subplots: </b>advance incrementally with each Scene. Scenes from different subplots are interspersed, so it's not necessarily apparent where events lie on the time scale, but subplots proceed more-or-less at the same rate.</p><p>Towards the middle of the story gossip in one subplot will give some perspective about what's happening in another subplot.</p><p>In the latter half of the middle section, subplots will begin to affect each other. Gradually all the subplots will coalesce into one large and complicated plot. Characters will be faced with more influences pushing them in different directions. Tension starts to rise as the competing interests clash.</p>"},		{"title": "The End", "descrip": "<p><b>The trajectory: </b>The chips from all the subplots fall into place. Now you can finally see how they were all connected from the beginning and how everything that happened was inevitable. Now it all makes sense; it couldn't have turned out any other way. On the other hand, things could never happen exactly this way again because the characters have all evolved along the way. Everything keeps changing; it's never really finished.</p><p><b>The Villains: </b>were foiled this time, but they've learned something by the experience. Next time perhaps they'll have given up their evil ways. Or maybe their evil skills will be that much sharper.</p><p><b>The Managers: </b>have not succeeded in their fevered plans. It turns out that an iron will won't make things happen without a certain amount of underlying willingness from the minions. Bribes and threats go only so far as a management strategy. The managers won't stop pressing for industry domination, of course, but next time maybe they'll spend a little more time considering what everyone else has at stake in the working relationship.</p> <p><b>The Lovers: </b>got what they asked for, but maybe not what they wanted. It turns out what they asked for was based on an old story they'd learned a long time ago. Now the story doesn't fit their present circumstances or the new ways they see themselves. It's like with favourite jeans that don't fit anymore, but kept in a trunk for the memory of when you always wore them.</p><p><b>The Avatars: </b>have become even more sophisticated in their analysis of human emotions. That's ominous in a way because it makes them even more powerful. At the same time, though, it makes them even more useful and valuable to us humans. They help us better understand other people, cooperate on common purposes and negotiate for what we want.</p>"},		
		{"title": "Monday", "descrip": "<b>Scene Set:</b><ul><li>Initial team meeting at XYCorp; characters introduced.</li><li>Lyre & Eager notice each other, have strong attraction.</li><li>Walf & Sarba are visibly lovy dovy in the meeting, which invites suspicion.</li><li>Eager visits Zero. They concoct a shurpa hack for fun.</li><li>Lyre visits Pool, discovers her shurpa running amok.</li></ul>"},
		{"title": "Tuesday", "descrip": "<b>Conflicts Launched:</b><ul><li>Lyre & Eager dare and tease each other into a date.</li><li>Walf & Sarba are caught in a compromising position at the office.</li><li>Lincoln & Forge change the project objective, which creates quesitons and doubt on the team.</li><li>Pool in more trouble with her shurpa.</li><li>Zero & Eager devise a customer intelligence pumping scheme.</li>"},
		{"title": "Wednesday", "descrip": "<b>Complications:</b><ul><li>Lyre & Eager discover they are not each other&apos;s prince & princess, in spite of strong love mental disorder.</li><li>Walf and Sarba are discovered, found in violation of the anti-frat rules and punished by Mother.</li><li>Eager questions whether the project objective is ethical, or even achievable. Showdown with Forge & Lincoln</li><li>Zero & Eager launch their customer intelligence hack.</li></ul>"},
		{"title": "Thursday", "descrip": "<b>More Complications:</b><ul><li>Lyre & Eager have tearful breakup, recriminations, but acknowlege they still have to work together at XYCorp.</li><li>Pool recognizes the stage of negotiation in Lyre & Eager&apos;s relationship, missed by Lyre&apos;s shurpa.</li><li>Lincoln wants team members to join the shurpa decryption lobby group and create embarrassing social media posts.</li><li>Lincoln discovers his customer intelligence program has been hacked.</li><li>Mother interrogates Lyre & Eager on suspicion.</li></ul>"},
		{"title": "Friday", "descrip": "<b>Impossible Situation:</b><ul><li>Lincoln freaks out on Forge over hacks and project delays.</li><li>The team makes plans behind Forge&apos;s back to propose a new project objective and realistic shedule.</li><li>Lyre & Eager support each other at work and discover they like this arrangement. Great sex that night.</li></ul>"},
		{"title": "Saturday", "descrip": "<b>Crisis:</b><ul><li>Forge calls a special team meeting and delivers his ultimatim.</li><li>The team threatens to quit en masse unless project objective changed and sanctions rolled back.</li><li>Forge escorted out by security. Lincoln appoints Lyre as new team lead.</li><li>Lyre & Eager more great sex that night.</li></ul>"},
		{"title": "Sunday", "descrip": "<b>Epilogue:</b><ul><li>Eager invited to supper at Pool&apos;s place.</li><li>Walf & Sarba get married.</li><li>Pool figures out basic shurpa programming.</li><li>Zero gets what he wanted.</li><li>Forge working as barrista.</li><li>Lincoln unchanged, without a clue.</li></ul>"}
    ]
}
